
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Mar 07 13:29:51 CET 2012
//----------------------------------------------------

package StratmasClient.TaclanV2;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int INTEGER = 4;
  public static final int EQUIV = 8;
  public static final int OPENBLOCK = 9;
  public static final int TRUE = 6;
  public static final int CLOSEBLOCK = 10;
  public static final int EOF = 0;
  public static final int STRING = 2;
  public static final int FALSE = 7;
  public static final int SCOPE = 12;
  public static final int ID = 3;
  public static final int error = 1;
  public static final int FROM = 14;
  public static final int AS = 13;
  public static final int IMPORT = 11;
  public static final int FLOAT = 5;
}

